name: Build and publish Docker image to Organisation registry

on:
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          # repository: ghcr.io/cnu-25
          repository: ghcr.io
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ github.ref_name }} # Match branch name
